### ISSUE TITLE
observers test fail

### ISSUE THREAD

**Issue by jonasbn** [jonasbn/perl-workflow#10]
This bug originates from: [rt.cpan.org RT:86758](https://rt.cpan.org/Ticket/Display.html?id=86758)

The problem is mentioned in the INCOMPATIBILITIES section of the documentation, but it is also observed with newer version perls (>5.8.8) and should be addressed.

jonasbn

**Comment by jonasbn** [comment]
The issue [is demonstrated](https://travis-ci.org/jonasbn/perl-workflow/jobs/341868493) by Travis CI.

**Comment by djzort** [comment]
Perl 5.8.8 is seriously ancient history. You may simply wish to set the minimum perl version to 5.10 or newer.

**Comment by ehuelsmann** [comment]
@djzort That's not a solution for this issue, because as @jonasbn mentions in the original description

> but it is also observed with newer version perls (>5.8.8)

So this issue is definitely real and to be investigated.

**Comment by jonasbn** [comment]
hi @djzort 

I prefer not to impose a version on people unless necessary. I normally use: [Perl::MinimumVersion](https://metacpan.org/pod/Perl::MinimumVersion)

```bash
 WORKFLOW  [jonasbn:~/develop … ub/perl-workflow] [perl-5.28.1] master+
± perlver lib


   ----------------------------------------------------------------------------
 | file                                          | explicit | syntax | external |
 | ---------------------------------------------------------------------------- |
 | lib/Workflow.pm                               | v5.6.0   | v5.6.0 | n/a      |
 | lib/Workflow/Exception.pm                     | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Validator.pm                     | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Config.pm                        | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister.pm                     | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Action.pm                        | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Factory.pm                       | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Context.pm                       | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Condition.pm                     | ~        | v5.6.0 | n/a      |
 | lib/Workflow/History.pm                       | ~        | v5.6.0 | n/a      |
 | lib/Workflow/State.pm                         | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Base.pm                          | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Validator/MatchesDateFormat.pm   | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Validator/HasRequiredField.pm    | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Validator/InEnumeratedType.pm    | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Config/Perl.pm                   | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Config/XML.pm                    | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Action/Null.pm                   | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Action/InputField.pm             | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Action/Mailer.pm                 | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Condition/HasUser.pm             | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Condition/LazyAND.pm             | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Condition/CheckReturn.pm         | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Condition/Evaluate.pm            | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Condition/LazyOR.pm              | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Condition/GreedyOR.pm            | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Condition/Nested.pm              | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister/DBI.pm                 | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister/SPOPS.pm               | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister/File.pm                | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister/RandomId.pm            | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister/UUID.pm                | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister/DBI/SequenceId.pm      | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister/DBI/AutoGeneratedId.pm | ~        | v5.6.0 | n/a      |
 | lib/Workflow/Persister/DBI/ExtraData.pm       | ~        | v5.6.0 | n/a      |
 | ---------------------------------------------------------------------------- |
 | Minimum explicit version : v5.6.0                                            |
 | Minimum syntax version   : v5.6.0                                            |
 | Minimum version of perl  : v5.6.0                                            |
   ----------------------------------------------------------------------------
```

As you can see the minimal Perl version is required is 5.6.0. This is also specified in `dist.ini` - I do however do CI test with a minimum Perl version of 5.14 since this is a requirement from some of the Dist::Zilla plugins I use for maintaining the distribution, but runtime requirement is set to 5.6.0 and as much as I would love to blame external dependencies and avoid them by bumping requirements, the issue here is with the Workflow code.

Take care

**Comment by ehuelsmann** [comment]
@jonasbn do you have a known setup to reproduce this issue? I don't have access to TravisCI anymore since they changed FOSS support strategy in November 2020.

**Comment by jonasbn** [comment]
Hi @ehuelsmann 

At time it does seem to be a _heisenbug_, I have not been able to demonstrate it locally, but [the reports from the CPAN-testers](http://www.cpantesters.org/distro/W/Workflow.html?grade=3&perlmat=2&patches=2&oncpan=2&distmat=2&perlver=ALL&osname=ALL&version=1.48) indicate that it exists.

**Comment by jonasbn** [comment]
Issue observed in latest release also:

REF: http://www.cpantesters.org/cpan/report/d97fb3b0-57d5-11eb-82aa-952a1f24ea8f

**Comment by ehuelsmann** [comment]
Running a truckload of test rounds on a newly built Perl 5.8.8, I can't reproduce this problem on my machine.

**Comment by ehuelsmann** [comment]
From the Slack channel:

I found the heisenbug with the observers.

In short: the problem stems from the use of Class::Observable in combination with adding observers on instances -- and the fact that the instances in our test suite end up in exactly the same address -- sometimes.

What I did was instrumenting the observer and the test suite with print statements. This is the output of a failed run:

```plain
t/workflow.t ....................... 1/39 cleared observations in SomeObserver
got "update" observation in SomeObserver:  SomeObserver Workflow=HASH(0x56290649a110) create 
got "sub" observation in SomeObserver:  Workflow=HASH(0x56290649a110) create 
# observations in SomeObserver: 2
got "update" observation in SomeObserver:  SomeObserver Workflow=HASH(0x56290659df48) fetch 
got "sub" observation in SomeObserver:  Workflow=HASH(0x56290659df48) fetch 
cleared observations in SomeObserver
# observations in SomeObserver: 0
got "update" observation in SomeObserver:  SomeObserver Workflow=HASH(0x56290649a110) fetch 
got "sub" observation in SomeObserver:  Workflow=HASH(0x56290649a110) fetch 
got "update" observation in SomeObserver:  SomeObserver Workflow=HASH(0x56290649a110) fetch 
got "sub" observation in SomeObserver:  Workflow=HASH(0x56290649a110) fetch 
# observations in SomeObserver: 4#   Failed test 'One observation sent on workflow fetch to two observers'
#   at t/workflow.t line 84.
#          got: '4'
#     expected: '2'
# $VAR1 = [
#           [
#             'class',
#             'Workflow',
#             'fetch'
#           ],
#           [
#             'sub',
#             'Workflow',
#             'fetch'
#           ],
#           [
#             'class',
#             'Workflow',
#             'fetch'
#           ],
#           [
#             'sub',
#             'Workflow',
#             'fetch'
#           ]
#         ];
```
(btw, line 84 in the error above is actually line 80 on master.)

What you see in the above is that a workflow instance is created in the "create" event on address 0x56290649a110; then the next one is being created in a "fetch" test on address 0x56290659df48. The failing test has a workflow which is located at **exactly** the same address as the one in the *create* test.

The question rises "why is that important"? Well, the key to the problem is in `Class::Observable`. The implementation of the way it tracks the observers is the problem, to be exact. Take a look at [Class::Observable line 20](https://metacpan.org/release/Class-Observable/source/lib/Class/Observable.pm#L20). There you see that the observers on instances and classes are tracked using

```perl
$O{ $item } ||= [];
```

Why is this a problem? Well, because in our case `$item` is a reference to a Workflow instance - which when used as a hash key is being stringified to `Workflow=HASH(0x56290649a110)`. Yet on the second round, that key already exists and 2 more observers are added.

**Comment by ehuelsmann** [comment]
@cwinters, this bug originates from a bug in `Class::Observable`. Is there a (GitHub) repository where we can contribute a fix?

**Comment by cwinters** [comment]
Hi @ehuelsmann - Even though I was the last releaser of Class::Observable I'm no longer its maintainer. Aristotle Pagaltzis (@ap) is, and it looks like he's got the code here: https://github.com/ap/Class-Observable

**Comment by ehuelsmann** [comment]
Hi @cwinters, Thanks for the quick response and pointing me/us in the right direction. Heading over to his repository now...

**Comment by ehuelsmann** [comment]
Filed a bugreport as ap/Class-Observable#1 and a PR as ap/Class-Observable#2 for the fix in Class::Observable.
