### ISSUE TITLE
Support for attributes in persister connections

### ISSUE THREAD

**Issue by jonasbn** [jonasbn/perl-workflow#109]
I have received a suggestion via e-mail. The suggestion was to support UTF-8 for persisters.

Since the DBI drivers (DBDs) are handling this very differently:

DBD::MySQL:

```perl
Schema->connect("dbi:mysql:".$db{db}, $db{user}, $db{pass}, {mysql_enable_utf8 => 1} );
```

- SQLite does it natively
- PostgreSQL uses an accessor
- Oracle uses environment variables

But I spotted that we do not feed the options/attributes to the DBI connect, perhaps this should be possible?

```perl
    my $dbh = eval {
               DBI->connect( $self->dsn, $self->user, $self->password )
            || croak "Cannot connect to database: $DBI::errstr";
    };
```

From lines 73-76 in Workflow::Persister::DBI

From [the DBI documentation](https://metacpan.org/pod/DBI#connect):

```perl
$dbh = DBI->connect($data_source, $username, $password, \%attr)
          or die $DBI::errstr;
```

**Comment by ehuelsmann** [comment]
Love the idea to support driver attributes!

For Pg, the driver already supports UTF-8 by default since 3.0.0 (2014-02-04) (see https://metacpan.org/pod/DBD::Pg#pg_enable_utf8-(integer)).
