### ISSUE TITLE
Undeclared dependency Data::UUID

### ISSUE THREAD

**Issue by eserte** [jonasbn/perl-workflow#13]
See subject. The compile test fails on lib/Workflow/Persister/UUID.pm if the module is not installed, so it has either to be declared as a prerequisite, or the failing test should be skipped if the prereqs are not met.

**Comment by jonasbn** [comment]
Thanks @eserte I will look into it

**Comment by jonasbn** [comment]
This have been addressed in release 1.45. Thanks for the issue report.
