### ISSUE TITLE
Workflow 1.46 tarball contains `local` directory

### ISSUE THREAD

**Issue by perlpunk** [jonasbn/perl-workflow#17]
### Description

The tarball for version 1.46 contains a `local` directory with installed modules.
That's probably accidental.

https://metacpan.org/release/JONASBN/Workflow-1.46
https://metacpan.org/source/JONASBN/Workflow-1.46/local

I stumbled over this while maintaining perl modules in the SUSE Open Build System https://build.opensuse.org/package/show/devel:languages:perl/perl-Workflow

**Comment by jonasbn** [comment]
This has been addressed in release 1.47, thank you for reporting.
