### ISSUE TITLE
Remove `fetch_extra_workflow_data()`

### ISSUE THREAD

**Issue by ehuelsmann** [jonasbn/perl-workflow#181]
# Issue Template

### Description

There's an API in the main persister `fetch_extra_workflow_data()`. This API is called by the DBI persister after having fetched its data from the database. My proposal is to remove this API because it is duplicated functionality:

The only way to implement this API is by creating a new class derived (directly or indirectly) from the DBI persister class. Yet, if a derivative has to be created in the first place, the generally accepted pattern would be to wrap the `fetch_workflow()` method:

```perl
sub fetch_workflow {
  my ($self, $wf_id) = @_;
  my $wf = $self->SUPER::fetch_workflow( $wf_id );

  ...; # fetch additional data

  return $wf;
}
```

Which requires the same derivative creation step, but sticks closer to generally accepted patterns of OOP.

**Comment by ehuelsmann** [comment]
There's an additional weirdness going on: the extra data gets stored in the `context` of the workflow. However, if the context gets correctly serialized, then why store the extra data double? Shouldn't the "extra data" be a facility orthogonal to the `context`?

**Comment by ehuelsmann** [comment]
Yet more notes: There's also some asymmetry going on: when is this data being serialized? In other words: shouldn't there be *at least* be something symmetric to *store* this data?

Since there's nothing like it, I'm advocating again to remove this method; for the storage side, I'm already overriding `create_workflow` and `update_workflow`.

**Comment by jonasbn** [comment]
Hi @ehuelsmann 

I sounds like a good idea to remove the extra data concept if it is redundant. By redundant you mean it is redundant with general context?
