### ISSUE TITLE
Move some constant candidates to central place

### ISSUE THREAD

**Issue by ehuelsmann** [jonasbn/perl-workflow#35]
# Issue Template

### Description

This issue comes from the old TODO file which didn't specify much more context.

**Comment by ehuelsmann** [comment]
@jonasbn was this handled by b6ce54a69c389736dd8d9bcc4c56c077dc191995 ?

**Comment by jonasbn** [comment]
@ehuelsmann for now, if we come up with more helpful constants we can find a way to share them, but lets say this is good for now.

**Comment by jonasbn** [comment]
Closed by PR #178
