### ISSUE TITLE
Add tests to increase coverage >85%

### ISSUE THREAD

**Issue by ehuelsmann** [jonasbn/perl-workflow#36]
# Issue Template

### Description

85% is a pretty industry accepted coverage, but to get there we need more tests.

(a little over 78% at the time of creation)

**Comment by ehuelsmann** [comment]
@jonasbn We're at 86.39 now! (see https://coveralls.io/builds/41750124); however, some part of `lib/` is included, which causes the total coverage being reported at 85%.

Two things. First: This goal has been realized and we can close this issue. Second: I'll have to check how to exclude `lib/` from coverage reporting.

**Comment by jonasbn** [comment]
Awesome!
