### ISSUE TITLE
Address Perl::Critic violations

### ISSUE THREAD

**Issue by jonasbn** [jonasbn/perl-workflow#43]
- [x] Address the sections marked with ## no critic scattered throughout the code base, this might be valid, but another perspective and suggestions for refactorings might be a good idea (patches?)
- [ ] follow up up Perl::Critic policies disabled and marked as TODO in the
  `t/perlcriticrc` file
- [x] Investigate whether use warnings pragma, breaks too much backwards
  compatibility `[TestingAndDebugging::RequireUseWarnings]`
- [ ] Investigate violations of Perl::Critic policy `[Subroutines::ProhibitExplicitReturnUndef]`
- [ ] Investigate violations of Perl::Critic policy `[ValuesAndExpressions::ProhibitMagicNumbers]`

**Comment by ehuelsmann** [comment]
@jonasbn with some of the PRs addressed, could you check off the check marks you consider completed, or detail what's left for any that I PR-ed for?

**Comment by jonasbn** [comment]
Ok, we still disable strictures in a few places as reported by [TestingAndDebugging::ProhibitNoStrict](https://metacpan.org/pod/Perl::Critic::Policy::TestingAndDebugging::ProhibitNoStrict)

**Comment by jonasbn** [comment]
We should not have any issues with [TestingAndDebugging::RequireUseWarnings] since we are requiring Perl 5.14
