### ISSUE TITLE
Investigate ability to inline more configuration instead of using files

### ISSUE THREAD

**Issue by jonasbn** [jonasbn/perl-workflow#49]
- Decide where to put the configuration for the built-in
  validators/conditions/actions? Should we make it part of the
  WorkflowFactory initialization process, maybe just keep the built-ins
  configured in a class that's distributed with the module? (We don't
  want to force people to reference a separate file every time...

**Comment by jonasbn** [comment]
Perhaps this is related to #37

**Comment by ehuelsmann** [comment]
Hasn't this been solved long ago by https://github.com/jonasbn/perl-workflow/blob/603c96e173b48fcbe52c53232d32fd4c89ec0304/lib/Workflow/Factory.pm#L933 ?

**Comment by jonasbn** [comment]
I will check it out

**Comment by ehuelsmann** [comment]
Given the lack of a description of the exact problem, I'm afraid I can't come up with an applicable solution. For me, this issue is insufficiently actionable. With all these years without activity, I'm closing it as clearly insufficiently urgent.
