### ISSUE TITLE
Make extra Action properties available to workflow-users

### ISSUE THREAD

**Issue by ehuelsmann** [jonasbn/perl-workflow#54]
# Issue Template

### Description

The documentation for `Workflow::Action` explicitly mentions - under the documentation for `new()` - the ability to pass extra properties. The example being the ability to add an `order` property which the UI can use to sort the actions. I want to do exactly that. See the example below, copied from the documentation:

```plain
<state name="INITIAL">
  <description>
    Manage Manufaturers
  </description>
  <action index="0" name="Browse" resulting_state="BROWSE">
    <condition name="roleis_oem_mgmt"/>
  </action>
  <action index="1" name="Create" resulting_state="CREATE">
    <condition name="roleis_oem_mgmt"/>
  </action>
  <action index="2" name="Back" resulting_state="CLOSED"/>
</state>
```

In order to access the index value, the consumer of the workflow needs to retrieve the `Workflow::Action` instances of the current state. The following methods return actions:

* `Workflow->get_current_actions()`  
  Returns action names only; doesn't provide access to the properties
* `Workflow->_get_action()`  
  Returns an action instance for the current state, but is documented to be internal; consumers can't depend on it
* `Workflow::Factory->get_action()`  
  Returns an action instance, but is documented to be internal; consumers can't depend on it -- additionally, the documentation doesn't say whether the action applies to the current state or not (and this being the factory, it could be a generically instantiated object)

# Bugs and Issues

### Specify what version was used

`1.49`

**Comment by jonasbn** [comment]
Closed by #56
