### ISSUE TITLE
RT:52558 Workflow::Persister::DBI reconnect implementation

### ISSUE THREAD

**Issue by jonasbn** [jonasbn/perl-workflow#8]
What is the simplest and most direct approach to dealing with  the case
where the mysql server hangs up on Workflow's persister?

"Failed to create workflow: DBD::mysql::st execute failed: MySQL server
has gone away at
/usr/local/lib/perl5/site_perl/5.10.0/Workflow/Persister/DBI.pm line 226."

1) It's not obvious to me where to configure reconnect.  
2) If reconnect wasn't an option, I can't see how to tell workflow to
reconnect to the underlying database.

Possible solution, sent to list for evaluation:

http://sourceforge.net/mailarchive/forum.php?thread_name=E9C55B97-0DD1-49E9-9F24-DE3FAE982534%40gmail.com&forum_name=perl-workflow-devel

**Comment by ehuelsmann** [comment]
This can actually be configured in the DSN (for MySQL/MariaDB): "dbi:mysql(mysql_auto_reconnect=>1):...".

See https://metacpan.org/pod/DBD::mysql#mysql_auto_reconnect and https://metacpan.org/pod/DBI#parse_dsn ; the latter most notably regarding the documentation of `attr_str`.

A generic implementation requires work throughout the code base to implement retry-loops or reconnect-checks. Let me know if this is still desired. (Note that given the structure of my own use of the library, I don't have any value for this feature at this time.)

**Comment by ehuelsmann** [comment]
@jonasbn ping?

**Comment by ehuelsmann** [comment]
@oliwel do you have a reconnect scheme in place that you think is ready for promotion into Workflow?

**Comment by melutovich** [comment]
@ehuelsmann 

Not everyone will want to turn on the reconnect, so it would need to have a config to turn on / off...

Recently, based on your 2021 comment and other sources, the way we did this (we already had our own persister subclass anyway)

package CatTxA::Wflow::Persister::CatalystDBIPersister;

use base qw( Workflow::Persister::DBI );

....

sub init {
    my ( $self, $params ) = @_;
    $self->SUPER::init($params);
    if ( $self->handle ) {
        $self->handle->{mysql_auto_reconnect} = 1;
    }
}

**Comment by ehuelsmann** [comment]
@melutovich Thanks for your feedback!

The fact that everybody can write their own persister, combined with the fact that e.g. MySQL/MariaDB implements a reconnect option, probably means that this is sufficiently available for "simple" use-cases. Anybody wanting to run against other, more complex databases would probably be able to spend some time and contribute back a solution to the project.

Closing the issue as "the part that the project considers within its scope has been addressed'.

**Comment by melutovich** [comment]
@ehuelsmann Am I correct that support for this got easier with https://github.com/perl-workflow/perl-workflow/issues/109

**Comment by ehuelsmann** [comment]
@melutovich yes. With that change, you can set the mysql_auti_reconnect option on initial connect(), indeed.
