### ISSUE TITLE
Investigate performance impact of removal of `is_debug` calls (and friends)

### ISSUE THREAD

**Issue by ehuelsmann** [jonasbn/perl-workflow#89]
# Issue Template

### Description

The code base is littered with calls to `is_debug()` and friends before actually calling the logger's `debug()` output function. While this pattern prevents extensive log message generation in some cases (like calling `Data::Dumper::Dumper()`), it mostly prevents string interpolation and often even not that.

For string interpolation, there is the option to either accept the downside as negligible performance loss or to split the string into parts and pass the parts as arguments to the logger. Some logging invocation calls already do this.

Point of this issue is to determine what the performance loss actually amounts to, in various logging scenarios.

**Comment by jonasbn** [comment]
I did some very basic and _unscientific benchmarking_ on the test suite, I could not see any impact at all.

Branch (PR #108):

```
Files=42, Tests=605, 18 wallclock secs ( 0.17 usr  0.07 sys + 17.94 cusr  2.64 csys = 20.82 CPU)
Files=42, Tests=605, 17 wallclock secs ( 0.17 usr  0.06 sys + 18.14 cusr  2.64 csys = 21.01 CPU)
Files=42, Tests=605, 16 wallclock secs ( 0.16 usr  0.07 sys + 17.92 cusr  2.56 csys = 20.71 CPU)
Files=42, Tests=605, 17 wallclock secs ( 0.16 usr  0.06 sys + 18.37 cusr  2.66 csys = 21.25 CPU)
Files=42, Tests=605, 16 wallclock secs ( 0.16 usr  0.07 sys + 17.60 cusr  2.45 csys = 20.28 CPU)
```

Master:

```
Files=42, Tests=611, 17 wallclock secs ( 0.17 usr  0.07 sys + 17.84 cusr  2.55 csys = 20.63 CPU)
Files=42, Tests=611, 20 wallclock secs ( 0.17 usr  0.08 sys + 20.06 cusr  3.06 csys = 23.37 CPU)
Files=42, Tests=611, 17 wallclock secs ( 0.16 usr  0.07 sys + 18.06 cusr  2.59 csys = 20.88 CPU)
Files=42, Tests=611, 17 wallclock secs ( 0.17 usr  0.08 sys + 18.15 cusr  2.64 csys = 21.04 CPU)
Files=42, Tests=611, 17 wallclock secs ( 0.16 usr  0.08 sys + 18.18 cusr  2.62 csys = 21.04 CPU)
```
